# Generated by Django 5.1.4 on 2025-01-12 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        help_text="insert name of the author",
                        max_length=150,
                        verbose_name="Author name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
                "ordering": ["author_name"],
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Insert title of the post",
                        max_length=200,
                        verbose_name="Post titles",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Insert content of the post",
                        verbose_name="Full content",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        help_text="Upload picture",
                        null=True,
                        upload_to="images/",
                        verbose_name="Post images",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Insert date and time when post is created",
                        verbose_name="Date of creating a post",
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Amount of views"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Insert author of the post",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authors",
                        to="blog.author",
                        verbose_name="Author of the post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["title", "author"],
            },
        ),
    ]
