# Generated by Django 5.1.4 on 2025-01-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="author",
        ),
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["title"],
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
        migrations.AlterField(
            model_name="blog",
            name="picture",
            field=models.ImageField(
                blank=True,
                help_text="Upload picture",
                null=True,
                upload_to="blog/images/",
                verbose_name="Post images",
            ),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
    ]
