# Generated by Django 5.1.4 on 2025-02-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_blog_author_alter_blog_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="picture",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="images/%Y/%m/%d/",
                verbose_name="Saved image",
            ),
        ),
    ]
