# Generated by Django 5.1.4 on 2025-02-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="picture",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="blog/images/%Y/%m/%d/",
                verbose_name="Saved image",
            ),
        ),
    ]
