# Generated by Django 5.1.4 on 2025-01-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="images/%Y/%m/%d/",
                verbose_name="Saved image",
            ),
        ),
    ]
