# Generated by Django 5.1.4 on 2025-02-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_is_published",
            field=models.BooleanField(default=False),
        ),
    ]
